language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings .m2/travis-settings.xml'
install: true
env:
  global:
  - secure: OQtCtnNr+v5zVqRDBN5ya33nidP11Yl/csn3xysCTHejjF3N337FFHrlwDTkVDiFuZhgYVk3IKbsWK5I1wJ0H0oDobc3zsxqppYAXM4IztV2DCpmy3h8P87I3aQquOybVF4asBhdRkPwo5YjOfc0/Wgb7Fb4kOVvWLyPH1dr9UvkR+Ldted0hfviMXI9nUFS2YanzMC3C+HnARR8SqrTJnI+Q1FppjBZdWcJKfm5jp70eydsd4EJZZ7B82ki47jTxUaOz8+cWUIOpwfiyTPTbXDrjAmA57JPk1xIvbbs8s8sl5EEWN2U/DV9g9RIyxCEnxCCJ5p5K275mvfV1QWYfYKlOCcEN+UjMUtJrXnPCpo6AVWO2Xk2dRU7/52DKZOQyA/GbKA6mxZkNhvn3CXX2Oy49xJuOPMbvBvw4TcBfoyCmcYEi+H5D40ZzlAuc7yTuruiD8b3DElKjQL6+LxU8i6voeE1b0ZZSgFDn8/fgBGXx/DPpfI5NUABFIeO6Fce+ajEVWYzumSBucahZ6abd0zCddUHbykwpJffPehVm0KGVEjQr/m65w9MqBuAOvNLy9T+abhk9WPKJvwhAO4CaJsRz8ZEvmDh1LwThBWRfRWaF8LyPsBD+q2zWbMVLTjlNy0X56Aula0eSqKhGe5wmgusdAef9kBRsHhwgemFuxY=
  - secure: mgMZbounK3lVKav6M47CgilPCdgw7ipSLddbxEGJspVg+inZtyrCVR0NvvPWyTJyNzNoTcVarpoyB8XxjB8jLiDNxJh34ADWg7Jp4u1LMVu2xfOUd3vwcA6fmG7tYvfrOk/rua1mERxMI8VI9TdYpcY7k287pzPfEK+wgNeWE2liGWp4xz88zUAC/0sFr6V0eS2jlZW+mDmiKRzUZ9vGIw86gI1WGEIVQ2fY6vW+C9lqPHmfcX0GInHr5wmk4Q7heVadUemg+YmIIZH0NMQWnSxi7YSe88B0RyitLwXfB7rCbyKpFa7iWRzDnjrxHZ4LOLc4YZp2j3JoybkfvmKK3Pz0WWe82RxCtPu/mA7qM8j0SYRRzXdorWLZSfvPyXs3iaG0fURQN2gO+G0XW8yo5ISg2NeiLmF9CyIE54AouwaFLzzgHhuvny62k8BWAGsLlfMVxZM5fWX8i7hogF2ZaTP1DTEs7ZBuIzythv7mDHuPU8bm2J5wyNrlwaE2/1EGJUr0SEGYvCC25TG2R6wp3DWWtXl6BdEB0msj036CUV9WAR8jkg1t8cBceUR7excbyGLli4oIYGdz+li1zxKxhbdAxP0i0dbcf60gcKLroUiR+s2Z07Dixm/TNA+b88ccz8QWC+k6UkKcJuv7ZjkCvVFurUbSs6uBKMR5mIcYCgQ=
